# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = " îœ‘ $all"

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[ âŒ˜](bold green)"  # Fixed lambda symbol on success
error_symbol = "[ âŒ˜](bold red)"     # Lambda symbol for errors

[status]
symbol = "[âŸ³](bold yellow)"

[git_branch]
symbol = 'î©¨ '
style = 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[rust]
format = 'via [ğŸ¦€ $version $toolchain ](red bold)'  
